### ISSUE TITLE
error: ‘SNDRV_DMA_TYPE_VMALLOC’ undeclared

### ISSUE THREAD

**Issue by HinTak** [HinTak/sound-usb-dkms#1]
breakage from recent 5.4 changes:

```
sound/usb/pcm.c: In function ‘snd_usb_preallocate_buffer’:
sound-usb-dkms/sound/usb/pcm.c:1806:36: error: ‘SNDRV_DMA_TYPE_VMALLOC’ undeclared (first use in this function); did you mean ‘SNDRV_DMA_TYPE_DEV_UC’?
   snd_pcm_lib_preallocate_pages(s, SNDRV_DMA_TYPE_VMALLOC,
                                    ^~~~~~~~~~~~~~~~~~~~~~
                                    SNDRV_DMA_TYPE_DEV_UC
sound-usb-dkms/sound/usb/pcm.c:1806:36: note: each undeclared identifier is reported only once for each function it appears in
make[1]: *** [scripts/Makefile.build:281: sound-usb-dkms/sound/usb/pcm.o] Error 1
```

Last commit that works with 5.3.10 header is 49a73336e2faba96e561d8a34e3e8f9c6c2f899a , i.e. roll back three commits, to "sync to v5.4-rc2-1490-g71a6169911c3 / sound-5.4-rc5-1455-g71a6169911c3".
